### ISSUE TITLE
Namespaces in DefaultDefinition Class input file

### ISSUE THREAD

**Issue by worxco** [EclipseGc/Classiphpy#1]
I notice that your PHP array for $data starts with a default that has a namespace of "EclipseGC".
Would it not be possible then, to use this as a TLN (Top Level Namespace) and in each of your following "classes" definitions, assume the "EclipseGC" as a TLN, thereby allowing you to state only "Person" and "Animal" in your example classes?

**Comment by EclipseGc** [comment]
Yeah, it just depends on how you want to parse it, the PSR4 parser is looking at the base namespace vs the class namespace and trying to create the proper directory structure, but if you are using your own DefinitionInterface implementation, then determining that namespace is 100% in your hands, so your data could break it down that way if you like.
